<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hw1" nsURI="http://www.example.org/hw1" nsPrefix="hw1">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PhoneNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="meals" lowerBound="10"
        upperBound="65" eType="#//Meals"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="musicband" lowerBound="1"
        eType="#//MusicBand"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="photos" upperBound="50"
        eType="#//Photos"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payment" lowerBound="1"
        eType="#//Payment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refund" lowerBound="1"
        eType="#//Refund" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Refund">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RefundId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Singer" eSuperTypes="#//Staff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="musicband" lowerBound="1"
        eType="#//MusicBand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SingerList" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Photographer" eSuperTypes="#//Staff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="photographer" lowerBound="2"
        upperBound="6" eType="#//Photos" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Payment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PaymentId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refund" lowerBound="1"
        eType="#//Refund" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MusicBand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="inv1"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="inv1" value="self.Songs&lt;10 and self.Songs>0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Songs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Staff" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Salary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chef" eSuperTypes="#//Staff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="chef" lowerBound="1" eType="#//Meals"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Meals">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dessert" eSuperTypes="#//Meals">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="inv2"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="inv2" value="Dessert->exists(Name='Cheesecake')"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Counter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Photos">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="inv3"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="inv3" value="if self.Photoshots>50 then Photos->forAll(Location='London') else Photos->forAll(Location='oxford') endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Photoshots" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainCourse" eSuperTypes="#//Meals">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="inv4"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="inv4" value="self.Counter->size()&lt;5"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Counter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
</ecore:EPackage>
